In [2]:
import numpy as np

In [6]:
np_2d=np.array([[1.73,1.68,1.71,1.89,1.79],
                [65.4,59.2,63.6,88.4,68.7],
                [50,39,29,75,29]]
                )


In [7]:
np_2d

array([[ 1.73,  1.68,  1.71,  1.89,  1.79],
       [65.4 , 59.2 , 63.6 , 88.4 , 68.7 ],
       [50.  , 39.  , 29.  , 75.  , 29.  ]])

In [ ]:
np_2d.shape # aqui me dara las filas y las columnas Es diferente un atributo como este que un metodo que tiene corchetes despues

(3, 5)

In [ ]:
#subconjuntos
np_2d[:,1:3]  
#Aqui lo que quiero son todas las columnas por eso se ponen los dos renglones iniciales
# Le renglon 2 y 3 que corresponden alos inidices 1 y 2 

array([[ 1.68,  1.71],
       [59.2 , 63.6 ],
       [39.  , 29.  ]])

In [10]:
# ahora quiero todos los renglones pero de la fila 3 
np_2d[2,:]

array([50., 39., 29., 75., 29.])