In [1]:
import numpy as np
#los a arrays dee Numpy son muy poderosos
#asume que los la matriz tiene el mismo tipo de dato

In [2]:
np_2d=np.array([[1.73,1.68,1.71,1.89,1.79],
                [65.4,59.2,63.6,88.4,68.7],
                [50,39,29,75,29]]
                )


In [15]:
np_2d.shape

(3, 5)

In [4]:
np_2d.shape # aqui me dara las filas y las columnas Es diferente un atributo como este que un metodo que tiene corchetes despues

(3, 5)

In [ ]:
#subconjuntos
np_2d[:,1:3]  
#Aqui lo que quiero son todas las columnas por eso se ponen los dos renglones iniciales
# Le renglon 2 y 3 que corresponden alos inidices 1 y 2 

array([[ 1.68,  1.71],
       [59.2 , 63.6 ],
       [39.  , 29.  ]])

In [6]:
# ahora quiero todos los renglones pero de la fila 3 
np_2d[2,:]

array([50., 39., 29., 75., 29.])

In [13]:
print(np_2d)

[[ 13.84  13.44  13.68  15.12  14.32]
 [523.2  473.6  508.8  707.2  549.6 ]
 [400.   312.   232.   600.   232.  ]]


In [14]:
print(type(np_2d))

<class 'numpy.ndarray'>
